# fly.toml app configuration file generated for taskmaster on 2024-11-14T21:47:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taskmaster'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
